### ISSUE TITLE
Allow for segmentations to be resumed

### ISSUE THREAD

**Issue by kmader** [4Quant/LungStageAnnotator#3]
Right now they can only be saved, it would be nice if there were a resume feature

**Comment by kmader** [comment]
added resume segmentations, this is important for the first 6 since we need to resave them to get the right training data

**Comment by kmader** [comment]
Button works, but cannot continue segmentation after resuming!

**Comment by kmader** [comment]
Main problem appears to be that the reloaded file does not have the right segmentation node pointer (and thus no labels available)
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "petct_annotator.py", line 511, in get_label_ids
    return _get_segments(self.get_seg_node().GetSegmentation())
  File "petct_annotator.py", line 1488, in _get_segments
    seg_data.GetSegmentIDs(t_varray)
AttributeError: 'vtkCommonCorePython.vtkObject' object has no attribute 'GetSegmentIDs'
```

**Comment by kmader** [comment]
the core problem is a slicer issue: https://www.na-mic.org/Mantis/print_bug_page.php?bug_id=4271
